### ISSUE TITLE
Facebook graph debugger issue

### ISSUE THREAD

**Issue by lqez** [sprintseoul/sprintseoul.org#13]
Putting `https://sprintseoul.org` on https://developers.facebook.com/tools/debug/og/object/ will get `www.sprintseoul.org` as a canonical URL.

And also will get some errors: `Could Not Follow Redirect Path` and `Circular Redirect Path`

I have no idea to debug this.
Could you invite me to the Netlify team of `sprintseoul.org`?

<img width="1027" alt="Screen Shot 2019-10-02 at 11 08 44 PM" src="https://user-images.githubusercontent.com/579366/66051539-084bf300-e56a-11e9-9881-ea7f3126fc0b.png">

**Comment by lqez** [comment]
It looks like the Netlify domain set as `www.sprintseoul.org`, not `sprintseoul.org`.

**Comment by outsideris** [comment]
Fixed!
Sorry for late fixing.
